name: Python CI

on:
  push:
    branches:
      - '**'
    pull_request:
      branches:
        - tibo

jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      # 1ère étape : Set-up Python & Github project?
      - name: Set up Python 3.8 
        uses: actions/setup-python@v2 # Cette étape utilise l'action actions/checkout@v2 pour récupérer le code source de votre dépôt (github). Cela permet aux étapes suivantes d'accéder au code source pour effectuer des actions comme l'installation des dépendances et l'exécution des tests.
        with:
          python-version: 3.8
      # 2ème étape : Install Requirements
      - name: Install Requirements 
        run: | # le pipe | permet de "chaîner" plusieurs commandes à run en une seule fois
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # 3ème étape : Run les tests
      - name: Run Tests 
        run: pytest 




